import path from "path"
import fs from "fs/promises"
import { Session } from "../session"
import { MessageV2 } from "../session/message-v2"
import { Instance } from "../project/instance"
import { UI } from "../cli/ui"
import { EOL } from "os"

function formatDate(timestamp: number): string {
  return new Date(timestamp).toISOString().replace("T", " ").replace(/\.\d+Z$/, " UTC")
}

function extractFilesModified(messages: MessageV2.WithParts[]): string[] {
  const files = new Set<string>()
  for (const message of messages) {
    for (const part of message.parts) {
      if (part.type !== "tool") continue
      if (part.state.status !== "completed") continue
      const input = part.state.input
      if (input.filePath) files.add(input.filePath)
      if (input.file_path) files.add(input.file_path)
      if (input.path) files.add(input.path)
    }
  }
  return [...files].sort()
}

function extractToolsUsed(messages: MessageV2.WithParts[]): Record<string, number> {
  const tools: Record<string, number> = {}
  for (const message of messages) {
    for (const part of message.parts) {
      if (part.type !== "tool") continue
      tools[part.tool] = (tools[part.tool] || 0) + 1
    }
  }
  return tools
}

function extractKeyOutputs(messages: MessageV2.WithParts[]): string[] {
  const outputs: string[] = []
  for (const message of messages) {
    if (message.info.role !== "assistant") continue
    for (const part of message.parts) {
      if (part.type !== "text") continue
      if (part.text.length < 20) continue
      const trimmed = part.text.length > 500 ? part.text.slice(0, 500) + "..." : part.text
      outputs.push(trimmed)
    }
  }
  return outputs
}

export async function exportReport(sessionID: string) {
  const sessionInfo = await Session.get(sessionID)
  if (!sessionInfo) {
    UI.println(UI.Style.TEXT_DANGER + "Session not found: " + sessionID + UI.Style.TEXT_NORMAL)
    return
  }

  const messages = await Session.messages({ sessionID })
  const filesModified = extractFilesModified(messages)
  const toolsUsed = extractToolsUsed(messages)
  const keyOutputs = extractKeyOutputs(messages)

  // Count messages by role
  const userMessages = messages.filter((m) => m.info.role === "user").length
  const assistantMessages = messages.filter((m) => m.info.role === "assistant").length

  // Calculate total cost
  let totalCost = 0
  for (const msg of messages) {
    if (msg.info.role === "assistant") {
      totalCost += msg.info.cost || 0
    }
  }

  // Build markdown report
  const lines: string[] = []
  lines.push(`# Session Report: ${sessionInfo.title}`)
  lines.push("")
  lines.push("## Summary")
  lines.push("")
  lines.push(`- **Session ID:** ${sessionInfo.id}`)
  lines.push(`- **Created:** ${formatDate(sessionInfo.time.created)}`)
  lines.push(`- **Updated:** ${formatDate(sessionInfo.time.updated)}`)
  lines.push(`- **Messages:** ${userMessages} user, ${assistantMessages} assistant`)
  lines.push(`- **Total Cost:** $${totalCost.toFixed(4)}`)
  lines.push("")

  if (filesModified.length > 0) {
    lines.push("## Files Modified")
    lines.push("")
    for (const file of filesModified) {
      lines.push(`- \`${file}\``)
    }
    lines.push("")
  }

  const sortedTools = Object.entries(toolsUsed).sort(([, a], [, b]) => b - a)
  if (sortedTools.length > 0) {
    lines.push("## Tools Used")
    lines.push("")
    lines.push("| Tool | Count |")
    lines.push("|------|-------|")
    for (const [tool, count] of sortedTools) {
      lines.push(`| ${tool} | ${count} |`)
    }
    lines.push("")
  }

  if (keyOutputs.length > 0) {
    lines.push("## Key Agent Outputs")
    lines.push("")
    for (const output of keyOutputs.slice(0, 10)) {
      lines.push("> " + output.split("\n").join("\n> "))
      lines.push("")
    }
  }

  lines.push("---")
  lines.push(`*Generated by Lobster on ${formatDate(Date.now())}*`)
  lines.push("")

  const markdown = lines.join(EOL)

  // Save to .lobster/reports/
  const reportsDir = path.join(Instance.directory, ".lobster", "reports")
  await fs.mkdir(reportsDir, { recursive: true })

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-")
  const filename = `${timestamp}.md`
  const filepath = path.join(reportsDir, filename)

  await Bun.write(filepath, markdown)

  UI.println(UI.Style.TEXT_SUCCESS + "Report saved to: " + UI.Style.TEXT_NORMAL + filepath)
}
